name: cSpell
on: [pull_request]
jobs:
  cspell:
    runs-on: ubuntu-latest
    name: cspell
    steps:
      - uses: actions/checkout@v3
      - name: cspell
        uses: streetsidesoftware/cspell-action@v2
        with:
          root: packages
